# Generated by Django 4.0.4 on 2022-05-28 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('jobName', models.CharField(max_length=50)),
                ('jobLocation', models.CharField(max_length=50)),
                ('jobDescription', models.CharField(max_length=500)),
                ('experienceRequired', models.CharField(max_length=10)),
                ('skillsRequired', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='companyName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
