# Generated by Django 4.0.4 on 2022-05-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0002_jobmodel_employee_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='jobDescription',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='jobLocation',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='skillsRequired',
            field=models.TextField(max_length=100),
        ),
    ]
