# Generated by Django 4.0.4 on 2022-05-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_alter_jobmodel_jobdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='defaultApplicationForm',
            field=models.CharField(choices=[(0, 'Default Application Form'), (1, 'Customise Application Form')], default=0, max_length=2),
            preserve_default=False,
        ),
    ]
